### ISSUE TITLE
Proposal for thunderbird action

### ISSUE THREAD

**Issue by ceever** [stefonarch/custom-actions#1]
Hi there

Thanks for the valuables action examples.

I believe if you were to put <pre>MimeTypes=all/allfiles;</pre>the selection would be more perfect.

With the existing setting one cannot select several files of different types.

Cheers

**Comment by stefonarch** [comment]
That's true, I'll change it. But I have to say that for me multiple attachments never worked.
Does it work for you, and if yes which OS/DE?

**Comment by ceever** [comment]
True, did not pay attention to this. :-D I will try to understand the issue and get back to you.

**Comment by ceever** [comment]
It seems that %U cannot be joined into a "file:// ...,file://... ..." string. Thus, i created an intermediate script thunderbird.sh that parses %U:
<pre>#!/bin/bash

STRG=
for fo in "$@"
do
	STRG=$STRG,file://$fo
done

thunderbird -compose "attachment='${STRG:1}'"</pre>

Works.

**Comment by stefonarch** [comment]
It does not for me... error msg: file1 file2 does not exist.

**Comment by ceever** [comment]
Strange ... see my complete code attached. I am using PCManFM-Qt 0.14.1.

/home/aj/.local/share/file-manager/thunderbird.sh :
<pre>
#!/bin/bash

STRG=
for fo in "$@"
do
	STRG=$STRG,file://$fo
done

thunderbird -compose "attachment='${STRG:1}'"
</pre>
/home/aj/.local/share/file-manager/actions/thunderbird-attachement.desktop :
<pre>
[Desktop Entry]
Type=Action
Name=Send with Thunderbird
Icon=thunderbird
Profiles=foo;

[X-Action-Profile foo]
Exec=/home/aj/.local/share/file-manager/thunderbird.sh %U
MimeTypes=all/allfiles;
</pre>

**Comment by stefonarch** [comment]
Ok, it works, I've omitted the %U in the .desktop file Exec= line.

**Comment by ceever** [comment]
Mhhh, ok. But how are the file names passed then. Weird 🤷

**Comment by stefonarch** [comment]
Done in https://github.com/stefonarch/custom-actions/commit/a21e6be693daf3b1c417ebcab445e72bd40fd711, sorry for the delay.
