### ISSUE TITLE
disk usage not working anymore

### ISSUE THREAD

**Issue by stefonarch** [stefonarch/custom-actions#5]
`Exec=filelight %f` does nothing.
https://specifications.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html#exec-variables

**Comment by tsujan** [comment]
The reason should be that there's no `[X-Action-Profile profile-zero]` after `Profiles=profile-zero;` in it — A typo?

Also, add `Name=Default profile` to its end.

**Comment by stefonarch** [comment]
No success, tried also with qdirstat
```
[Desktop Entry]
Type=Action
Name=View disk usage
Name[it]=Visualizza utilizzo disco

Icon=filelight

Profiles=profile-zero;[X-Action-Profile profile-zero]
MimeTypes=inode/directory;

Exec=filelight %f

Name=Default profile

```

**Comment by tsujan** [comment]
This is mine, and works fine:

```

[Desktop Entry]
Type=Action
TargetLocation=true
Icon=baobab
Tooltip=Disk usage
ToolbarLabel=Disk usage
Name=Disk usage
Profiles=profile-zero;

[X-Action-Profile profile-zero]
SelectionCount==1
MimeTypes=inode/directory;
Exec=filelight %f
Name=Default profile
```

`[X-Action-Profile profile-zero]` is misplaced in your case.

**Comment by stefonarch** [comment]
Also this doesn't work here, I suspect there is something else interfering.

**Comment by tsujan** [comment]
Strange, as we both use Arch (Manjaro for me, but it isn't different from Arch)!

> I suspect there is something else interfering.

An altered `org.kde.filelight.desktop` inside `~/.local/share/applications`, for example?

**Comment by stefonarch** [comment]
No, I installed qdirstat just to test this and it doesn't work too. Have to check on my debian PC though.

**Comment by tsujan** [comment]
So, it happens to you only on Debian? If so, there may be a difference in the desktop entries. If it also happens to you on Arch, we're dealing with magical powers ;)

**Comment by tsujan** [comment]
BTW, Microsoft made GitHub more enjoyable today. Now this menu can't be closed with Falkon:

![menus](https://github.com/stefonarch/custom-actions/assets/981076/89883e5c-289e-4bf2-b6bb-c1decbb123ac)

**Comment by stefonarch** [comment]
No, it's on arch that is doesn't work, have to check debian if it's the same or not.

**Comment by stefonarch** [comment]
On debian the original file (similar to yours) works fine. On a fresh user in arch not...

**Comment by Bluey26** [comment]
Hello, i also use Arch, and this custom action worked for me:

```
[Desktop Entry]
Type=Action
Name=file qdirstat
Icon=user-desktop
Profiles=profile-zero;

[X-Action-Profile profile-zero]
Exec=qdirstat %f
Name=Default profile
SelectionCount==1
```
The one involving filelight does not work for me, but i think its related to the program behavior, since `filelight file.pdf` drops, in the terminal:

`failed to openurl QUrl("file://.../.../.../file.pdf)`

with every file i tried (i suppose that program only scans folders? --> based in the GUI, that only show options to scan folders)

In the other hand, `qdirstat file.pdf ` shows the same information as the custom action.

`filelight test_folder` does work for me, so this should be possible too:

```
[Desktop Entry]
Type=Action
Name=file filelight
Icon=user-desktop
Profiles=profile-zero;

[X-Action-Profile profile-zero]
MimeTypes=inode/directory;
Exec=filelight %f
Name=Default profile
SelectionCount==1
```

Which also worked for me as custom action(it scans the selected folder and its files).

Bluey.

**Comment by stefonarch** [comment]
Actually I forgot that I opened this, I've fixed it locally in the same way as your example time ago, will upload it.

Thanks for the reminder :)

**Comment by stefonarch** [comment]
Should be fixed now (didn't test under debian though).
