### ISSUE TITLE
Set as Wallpaper shows color instead of background image

### ISSUE THREAD

**Issue by Bluey26** [stefonarch/custom-actions#7]
Hello.

As of today, using the 'set as wallpaper' custom action found in this repository does not show the background image, it is 'load as background' but the `--wallpaper-mode` is set, by default, into `color` mode (the background image was properly shown into the GUI, but the mode was "fill with background color only".

Adding `--wallpaper-mode=stretch` into the custom action found in here solves the problem, since it changes the wallpaper mode. 
The function, then, should be:

`pcmanfm-qt --wallpaper-mode=stretch -w %f`

Or any other wallpaper mode, but `color` one.

This was tested in: `pcmanfm-qt 1.4.0`

**Comment by stefonarch** [comment]
I can't reproduce it, it works still fine here with `Exec=pcmanfm-qt -w %f` but I'll update it to be on the safe side.
